import type { ProductInput } from "@/lib/inventory"

export const DEMO_PRODUCTS: ProductInput[] = [
  {
    name: "Laptop Stand",
    description: "Adjustable aluminum desk stand for laptops",
    sku: "ACC-LST-001",
    price: 2499,
    taxRate: 18,
    stockQty: 18,
    category: "Accessories",
  },
  {
    name: "Wireless Mouse",
    description: "Ergonomic 2.4 GHz wireless mouse",
    sku: "ACC-MOU-002",
    price: 799,
    taxRate: 18,
    stockQty: 42,
    category: "Accessories",
  },
  {
    name: "Mechanical Keyboard",
    description: "Compact mechanical keyboard with blue switches",
    sku: "ACC-KEY-003",
    price: 3499,
    taxRate: 18,
    stockQty: 16,
    category: "Accessories",
  },
  {
    name: "USB-C Hub",
    description: "7-in-1 USB-C hub with HDMI and card reader",
    sku: "ACC-HUB-004",
    price: 2199,
    taxRate: 18,
    stockQty: 24,
    category: "Accessories",
  },
  {
    name: "24-inch Monitor",
    description: "Full HD IPS office monitor",
    sku: "ELE-MON-005",
    price: 11999,
    taxRate: 18,
    stockQty: 9,
    category: "Electronics",
  },
  {
    name: "Office Chair",
    description: "Mesh-back ergonomic office chair",
    sku: "FUR-CHR-006",
    price: 8999,
    taxRate: 18,
    stockQty: 7,
    category: "Furniture",
  },
  {
    name: "A4 Copy Paper",
    description: "500-sheet premium printer paper ream",
    sku: "STN-PAP-007",
    price: 320,
    taxRate: 12,
    stockQty: 60,
    category: "Stationery",
  },
  {
    name: "Ink Cartridge Black",
    description: "High-yield black printer ink cartridge",
    sku: "STN-INK-008",
    price: 1450,
    taxRate: 18,
    stockQty: 20,
    category: "Stationery",
  },
  {
    name: "Desk Organizer",
    description: "Multi-compartment organizer for desk supplies",
    sku: "STN-ORG-009",
    price: 599,
    taxRate: 12,
    stockQty: 35,
    category: "Stationery",
  },
  {
    name: "Consulting Hour",
    description: "One hour of professional consulting service",
    sku: "SRV-CON-010",
    price: 2500,
    taxRate: 18,
    stockQty: 100,
    category: "Services",
  },
]
